name: Execute Spanner SQL

on:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: aerial-tide-461019-f7

    - name: Execute SQL from file
      run: |
        gcloud spanner databases execute-sql test-db \
          --instance=test-instance \
          --sql="$(cat queries.sql)"

Add workflow to Execute Spanner SQL
